export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const INCREASE_CART_QUANTITY = "INCREASE_CART_QUANTITY";
export const DECREASE_CART_QUANTITY = "DECREASE_CART_QUANTITY";
export const TOTAL_CART_AMOUNT = "TOTAL_CART_AMOUNT";
export const GET_AUTH_INFORMATION = "GET_AUTH_INFORMATION";
