"""empty message

Revision ID: 69977ed0051f
Revises: 1d27d9e07c6b
Create Date: 2021-10-11 16:14:41.511059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69977ed0051f'
down_revision = '1d27d9e07c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support', sa.Column('sentiment', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support', 'sentiment')
    # ### end Alembic commands ###
